name: "Deploy frontend"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Run frontend tests
        run: |
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.domeneshop.no
          username: accosta
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/client/
          server-dir: www/
          dry-run: true
